baseurl = "https://jj-coding-emporium.github.io/"
title = "Coding Emporium"
author = "J & J"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "colorful"
pygmentscodefences  = true

[params]
  sitename = "Coding Emporium"
  disableWebFonts = false
  description = "Coding Blog, specializing in JavaScript and Go."